name: LLM Automation Agent CI

on: [push, pull_request]  # Runs on every push and pull request

jobs:
  run-agent:
    runs-on: ubuntu-latest  # Use Ubuntu GitHub runner
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set API Token as Environment Variable
        run: echo "API_TOKEN=${{ secrets.API_TOKEN }}" >> $GITHUB_ENV

      - name: Run LLM Automation Agent
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}  # Ensure API_TOKEN is available to FastAPI
        run: |
          uvicorn app:app --host 0.0.0.0 --port 8000 &  
          sleep 5  # Wait for the server to start

      - name: Test API Endpoint
        run: |
          curl -X GET "http://127.0.0.1:8000/docs"
          curl -X GET "http://127.0.0.1:8000/run?task=extract_text_from_image"
