name: Run LLM Automation Agent

on: [push, pull_request]

jobs:
  run-agent:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run LLM Automation Agent
        run: |
          uvicorn app:app --host 0.0.0.0 --port 8000
